### ISSUE TITLE
Add a license file to the repo

### ISSUE THREAD

**Issue by mbrukman** [everpeace/cookbook-mesos#29]
Hi @everpeace, I noticed there's a note in the [License section of the README](https://github.com/everpeace/cookbook-mesos/blob/master/README.md#license) about the Apache license, but the reference to the full license is via URL (rather than a local file), and there are some issues with referencing documents via URLs, such as:

* their contents can change without the URL changing or any notification, or
* the site can move or become unavailable, and the content the URL is referencing is lost

Could you please add an explicit LICENSE file with the contents of the Apache license to this repo as well?

Thanks!

**Comment by everpeace** [comment]
Thanks @mbrukman !!

**Comment by mbrukman** [comment]
Thanks for adding the license file explicitly! I'm curious as to why you chose switch from Apache to MIT license? I'm fine with either of them; I'm just wondering why make the change.

Also, please note that there are a [bunch of files](https://github.com/everpeace/cookbook-mesos/search?utf8=%E2%9C%93&q=Do+Not+Redistribute&type=Code) in the repo that have this string:

> All rights reserved - Do Not Redistribute

This disallows forking/copying the repo; please update the file headers to specify the MIT license instead.

**Comment by everpeace** [comment]
> I'm just wondering why make the change.
After reading <http://choosealicense.com/>, I just selected MIT license because I don't care about any patents related things.
